{% set version = "3.1.1" %}

{% set mpi_prefix = "mpi_" + mpi %}

package:
  name: triqs
  version: {{ version }}

source:
  url: https://github.com/TRIQS/triqs/releases/download/{{ version }}/triqs-{{ version }}.tar.gz
  sha256: cf4f6064ea962fc088e0c2833bf7c4e52f4c827ea331bf3c57d1c9303649042b

build:
  number: 5
  skip: true  # [win or py<30]

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clangxx  # [osx]
  host:
    - boost-cpp
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - gmp
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - mako
    - importlib-metadata  # [py<38]
    - mpi4py
    - numpy
    - {{ mpi }}
    - python
    - scipy
    - libblas
    - liblapack
    - libclang
    - zlib
  run:
    - boost-cpp
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - gmp
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - mako
    - importlib-metadata  # [py<38]
    - mpi4py
    - {{ pin_compatible("numpy") }}
    - {{ mpi }}
    - python
    - scipy
    - matplotlib-base
    - libclang
    - zlib
    - {{ compiler('cxx') }}

test:
  imports:
    - triqs

about:
  home: https://triqs.github.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Toolbox for Research on Interacting Quantum Systems

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
