{% set version = "3.3.1" %}

{% set mpi_prefix = "mpi_" + mpi %}

package:
  name: triqs
  version: {{ version }}

source:
  url: https://github.com/TRIQS/triqs/releases/download/{{ version }}/triqs-{{ version }}.tar.gz
  sha256: 740efb57c9af39f4086115f8167a55833e84558261e0564c7179d8c17f911539

build:
  number: 1
  skip: true  # [win or py<30 or (osx and x86_64)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scipy                                  # [build_platform != target_platform]
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ mpi }}                              # [mpi == 'openmpi' and build_platform != target_platform]
    - clangxx  # [osx]
  host:
    - libboost-headers
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - gmp
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - mako
    - importlib-metadata  # [py<38]
    - mpi4py
    - numpy
    - {{ mpi }}
    - python
    - scipy
    - libblas
    - liblapack
    - libclang
    - zlib
  run:
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - gmp
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - mako
    - importlib-metadata  # [py<38]
    - mpi4py
    - {{ mpi }}
    - python
    - scipy
    - matplotlib-base
    - libclang
    - zlib
    - {{ compiler('cxx') }}

test:
  imports:
    - triqs

about:
  home: https://triqs.github.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Toolbox for Research on Interacting Quantum Systems

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
    - thoemi09
