{% set version = "3.0.0" %}

{% set mpi_prefix = "mpi_" + mpi %}

package:
  name: triqs
  version: {{ version }}

source:
  url: https://github.com/TRIQS/triqs/releases/download/{{ version }}/triqs-{{ version }}.tar.gz
  sha256: 21239fb42ba73f84a77b63abce84c0d2b9162277233d5839aaf39e22e1be8128

build:
  number: 3
  skip: True  # [win or py<30]
  merge_build_host: True

requirements:
  build:
    - cmake
    - make
    # - clangxx >=8  # [osx]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - gmp
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - mako
    - mpi4py
    - numpy
    - {{ mpi }}
    - python
    - scipy
    - libblas
    - liblapack
    - libclang
    - zlib
  run:
    - boost-cpp
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - gmp
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - mako
    - mpi4py
    - {{ pin_compatible("numpy") }}
    - {{ mpi }}
    - python
    - scipy
    - matplotlib-base
    - libclang
    - zlib
    - {{ compiler('cxx') }}

test:
  imports:
    - triqs

about:
  home: https://triqs.github.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Toolbox for Research on Interacting Quantum Systems'

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
