{% set version = "3.0.1" %}

{% set mpi_prefix = "mpi_" + mpi %}

package:
  name: triqs
  version: {{ version }}

source:
  url: https://github.com/TRIQS/triqs/releases/download/{{ version }}/triqs-{{ version }}.tar.gz
  sha256: d555a4606c7ea2dde28aa8da056c6cc1ebbdd4e11cdb50b312b8c8f821a3edd2

build:
  number: 2
  skip: true  # [win or py<30]
  merge_build_host: true

requirements:
  build: []
  host:
    - cmake
    - make
    - clangxx >=8  # [osx]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - boost-cpp

    - fftw
    - fftw * {{ mpi_prefix }}_*
    - gmp
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - mako
    - mpi4py
    - numpy
    - {{ mpi }}
    - python
    - scipy
    - libblas
    - liblapack
    - libclang
    - zlib
  run:
    - boost-cpp
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - gmp
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - mako
    - mpi4py
    - {{ pin_compatible("numpy") }}
    - {{ mpi }}
    - python
    - scipy
    - matplotlib-base
    - libclang
    - zlib
    - {{ compiler('cxx') }}

test:
  imports:
    - triqs

about:
  home: https://triqs.github.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Toolbox for Research on Interacting Quantum Systems

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
